- name: Revert to saved game
  hosts: all
  become: yes
  tasks:

    - name: Stop game server
      ansible.builtin.systemd:
        state: stopped
        name: factorio
    
    - name: Find save game
      ansible.builtin.find:
        paths:
          - /opt/factorio-saves/saves
          - /opt/factorio-saves/archive
        patterns: "{{ game_id }}.zip"
    
    - name: Start game server
      ansible.builtin.systemd:
        state: started
        name: factorio