- name: Revert to saved game
  hosts: all
  become: yes
  tasks:

    - name: Stop game server
      ansible.builtin.systemd:
        state: stopped
        name: factorio
    
    - name: Overwrite save game
      ansible.builtin.scripts: ./scripts/revert.sh --savegame {{ game_id }}
    
    - name: Start game server
      ansible.builtin.systemd:
        state: started
        name: factorio