- name: Revert to saved game
  hosts: all
  become: yes
  tasks:

    - name: Stop game server
      ansible.builtin.systemd:
        state: stopped
        name: factorio
    
    - name: Overwrite save game
      command: rm -r /opt/factorio/saves
      command: cp `find /opt/factorio-saves/ -name '{{ game }}.zip'`
    
    - name: Start game server
      ansible.builtin.systemd:
        state: started
        name: factorio